version: '3.7'
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    env_file:
      - .ghostfolio.env
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/ghostfolio-db?sslmode=prefer
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 3443:3333
  postgres:
    image: postgres:12
    env_file:
      - .postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'

volumes:
  postgres:
