version: '2.1'
services:
  trilium:
    build:
      context: .
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/data
    ports:
      - "3388:8080"
    volumes:
      - - /portainer/Files/AppData/Config/trilium:/data

volumes:
  trilium:
