version: '2.1'
services:
  trilium:
    container_name: trilium
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - "3388:8080"
    volumes:
      - /portainer/Files/AppData/Config/trilium:/data
